# Generated by Django 4.2.27 on 2026-01-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='icon_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image URL instead of upload', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image URL instead of upload', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='icon_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image URL instead of upload', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='icon_url',
            field=models.URLField(blank=True, help_text='Alternative: Provide image URL instead of upload', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='agents/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='role',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='roles/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='teams/'),
        ),
    ]
