# Generated by Django 4.2.27 on 2026-01-26 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_agent_icon_url_profile_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='riot_id',
            field=models.CharField(blank=True, help_text="Your Riot ID name (e.g. 'Tyloo')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='riot_tag',
            field=models.CharField(blank=True, help_text='Tag starting with # followed by 2-5 characters', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Tag must start with # and be followed by 2-5 alphanumeric characters (e.g. #NA1, #1234)', regex='^#[a-zA-Z0-9]{2,5}$')]),
        ),
    ]
