# Generated by Django 4.2.27 on 2026-01-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_riot_id_profile_riot_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='riot_id',
            field=models.CharField(default='', help_text="Your Riot ID name (e.g. 'Tyloo')", max_length=50),
        ),
    ]
