# Generated by Django 4.2.27 on 2026-01-26 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_riot_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='riot_tag',
            field=models.CharField(blank=True, help_text='Tag starting with # followed by 2-5 characters', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Tag must start with # and be followed by 2-5 alphanumeric characters (e.g. #NA1, #12345)', regex='^#[a-zA-Z0-9]{2,5}$')]),
        ),
    ]
