# Generated by Django 4.2.27 on 2026-01-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_riot_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['custom_order', 'name']},
        ),
        migrations.AddField(
            model_name='team',
            name='custom_order',
            field=models.PositiveIntegerField(default=0, help_text='Higher numbers appear later in the list'),
        ),
    ]
