# Generated by Django 4.2.27 on 2026-01-28 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_team_options_team_custom_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Ability 1', 'Ultimate'", max_length=50)),
                ('key_binding', models.CharField(choices=[('C', 'C'), ('Q', 'Q'), ('E', 'E'), ('X', 'X')], max_length=1)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='abilities/')),
                ('icon_url', models.URLField(blank=True, help_text='Alternative: Provide image URL instead of upload', max_length=500, null=True)),
            ],
            options={
                'ordering': ['key_binding'],
            },
        ),
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': 'Abilities'},
        ),
        migrations.AddField(
            model_name='ability',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_abilities', to='profiles.abilitytemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='ability',
            unique_together={('profile', 'template')},
        ),
        migrations.RemoveField(
            model_name='ability',
            name='key_binding',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='order',
        ),
    ]
