# Generated by Django 4.2.27 on 2026-01-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_abilitytemplate_alter_ability_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='maps/')),
                ('icon_url', models.URLField(blank=True, help_text='Alternative: Provide image URL instead of upload', max_length=500, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='maps',
            field=models.ManyToManyField(blank=True, related_name='player_profiles', to='profiles.map'),
        ),
    ]
