# Generated by Django 6.0.2 on 2026-03-06 09:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_map_profile_maps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_id', models.CharField(default='', help_text="Your Riot ID name (e.g. 'Tyloo')", max_length=50)),
                ('riot_tag', models.CharField(blank=True, help_text='Tag starting with # followed by 2-5 characters', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Tag must start with # and be followed by 2-5 alphanumeric characters (e.g. #NA1)', regex='^#[a-zA-Z0-9]{2,5}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
