# Generated by Django 6.0.2 on 2026-02-24 11:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRiot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_id', models.CharField(max_length=50)),
                ('riot_tag', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Tag must start with # and be followed by 2-5 alphanumeric characters (e.g. #NA1, #12345)', regex='^#[a-zA-Z0-9]{2,5}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='riot_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
